# fly.toml app configuration file generated for little-hill-7726 on 2023-05-09T07:18:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "little-hill-7726"
primary_region = "lax"
kill_timeout = "5m0s"

[http_service]
  internal_port = 5432
  force_https = true
  auto_start_machines = true
