# fly.toml app configuration file generated for hidden-breeze-5955 on 2023-05-08T20:16:53-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hidden-breeze-5955"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true
