# fly.toml app configuration file generated for solitary-grass-9182 on 2023-05-07T20:27:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solitary-grass-9182"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true
