# fly.toml app configuration file generated for summer-wave-4549 on 2023-05-07T20:26:29-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "summer-wave-4549"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
