# fly.toml app configuration file generated for red-wind-293 on 2023-05-08T13:03:19-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-wind-293"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
