# fly.toml app configuration file generated for lingering-leaf-7039 on 2023-05-08T19:34:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-leaf-7039"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
