# fly.toml app configuration file generated for falling-meadow-2024 on 2023-05-08T20:16:01-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "falling-meadow-2024"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
