# fly.toml app configuration file generated for patient-rain-8052 on 2023-05-08T09:54:59-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-rain-8052"
primary_region = "lax"
kill_timeout = "5m0s"

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
