# fly.toml app configuration file generated for long-waterfall-1171 on 2023-05-08T20:13:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "long-waterfall-1171"
primary_region = "lax"
kill_timeout = "5m0s"

[http_service]
  internal_port = 5432
  force_https = true
  auto_start_machines = true
