# fly.toml app configuration file generated for shy-silence-2935 on 2023-05-08T20:18:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-silence-2935"
primary_region = "lax"

[env]
  DEFAULT_PROJECT_NAME = "Big test"
  testest = "testest"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
