# fly.toml app configuration file generated for wispy-waterfall-4837 on 2023-05-07T20:27:53-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-waterfall-4837"
primary_region = "lax"

[env]
  DEFAULT_ORGANIZATION_NAME = "N"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
