# fly.toml app configuration file generated for icy-forest-5008 on 2023-05-07T12:16:53-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "icy-forest-5008"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[http_service]
  internal_port = 8080
  force_https = true
