# fly.toml app configuration file generated for cold-wind-3917 on 2023-05-08T19:32:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-wind-3917"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[http_service]
  internal_port = 8080
  force_https = true
