# fly.toml app configuration file generated for black-pine-4669 on 2023-05-09T07:19:23-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "black-pine-4669"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[http_service]
  internal_port = 8080
  force_https = true
