# fly.toml app configuration file generated for wandering-river-240 on 2023-05-06T07:42:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wandering-river-240"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[http_service]
  internal_port = 8080
  force_https = true
